-- require('rose-pine').setup({
--   -- disable_background = true,
--   disable_italics = true,
--   dim_nc_background = false,
--   disable_float_background = true,
--   groups = {
--     background = 'base',
--     background_nc = '_experimental_nc',
--     panel = 'surface',
--     panel_nc = 'base',
--     border = 'highlight_med',
--     comment = 'muted',
--     link = 'iris',
--     punctuation = 'subtle',
--
--     error = 'love',
--     hint = 'iris',
--     info = 'foam',
--     warn = 'gold',
--
--     headings = {
--       h1 = 'iris',
--       h2 = 'foam',
--       h3 = 'rose',
--       h4 = 'gold',
--       h5 = 'pine',
--       h6 = 'foam',
--     }
--     -- or set all headings at once
--     -- headings = 'subtle'
--   },
-- })
